# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170411_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to=b'product'),
            preserve_default=False,
        ),
    ]
